### PR TITLE
Add even more effects for Philips Hue lights

### PR DESCRIPTION
**Pull request by hanskroner**
Barely a couple of days after merging the light effects introduced in May of 2024, new firmware (v1.222.2) has been released for Philips Hue lights that adds 4 new light effects:
* `cosmos`
* `enchant`
* `sunbeam`
* `underwater`

In addition to adding these new effects, [deCONZ is also renaming](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7956) the `fireplace` effect to `fire` to match the effect names used by the CLIP API v2.

### CODE REVIEW

**Comment by Kane610** [comment]
Was it your intention to mark the PR as draft?

**Comment by hanskroner** [comment]
Yes, I wanted to keep it as draft waiting for the changes to be merged in to deconz-rest-api first, just in case there are any changes there.

**Comment by hanskroner** [comment]
@Kane610 - [deCONZ v2.29.0-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.29.0-beta) is out with support for the 4 new effects. Nothing changed since I opened the PR, so this can be merged as-is.

**Review by Kane610 — APPROVED** [review]
Great!

**Comment by Kane610** [comment]
118 is released with more hue effects

**Pull request merged**
