### PR TITLE
Add support for Aqara FP1

### PR DESCRIPTION
**Pull request by Kane610**
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5928
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6070

https://dresden-elektronik.github.io/deconz-rest-doc/devices/xiaomi/xiaomi_rtczcgq11lm_fp1_presence_sensor/

### CODE REVIEW

**Comment by freddieleeman** [comment]
I hope this is the right place to post this. I've been trying to get the Aqara FP1 fully working for months now within Home Assistant, but it is only shown as a binary presence sensor. No details or settings are visible.

image
image

I'm running the latest dockerized stable versions of Home Assistant and deCONZ. Is this a Home Assistant issue, a pydeconz issue, or a configuration issue on my part?

**Comment by Kane610** [comment]
I've only added the support to the library so far. I need to also implement it on home assistant side

**Comment by freddieleeman** [comment]
Wow, that was insanely quick; thank you. Is this on your to-do list for the coming months? 😉

**Comment by Kane610** [comment]
Yes its on my to-do, hard to say when exactly unfortunately

**Comment by freddieleeman** [comment]
I know how it is. Thank you for your contributions; I'll be waiting patiently.

**Comment by Kane610** [comment]
> I know how it is. Thank you for your contributions; I'll be waiting patiently.

Would you mind open an issue and share how you would like it exposed in home assistant?

Here is a good example https://github.com/Kane610/deconz/issues/322

**Comment by freddieleeman** [comment]
Yeah, sure! I believe ZHA has a fully working integration, so I'll try and find some screenshots that could work as a template.

**Comment by omerome83** [comment]
I purchased 3 Aqara Human Presence Sensor FP1 sensors and they just arrived today. If I can provide any support or testing, please l
et me know.

I definitely would love to include these in my home automations.

**Pull request merged**
