### PR TITLE
Add support for test mode in (fire) sensor

### PR DESCRIPTION
**Pull request by valentingc**
This PR adds support for the test mode of fire/smoke sensors. The tests are created by mocking a Develco/Frient smoke alarm, model SMSZB-120.
The initial implementation of this PR was done by @madwizard-thomas in his PR https://github.com/Kane610/deconz/pull/188.

I took his PR as the base for my PR and

- renamed the test property to `in_test_mode`
- changed the method return type to be a strict bool
- set the default value of the test mode to be `False`.

### CODE REVIEW

**Review by Kane610 — APPROVED** [review]
Awesome! Looks good!

**Comment by Kane610** [comment]
I think I have a couple of changes in pydeconz that I might want to change prior to a release, I will try to get it done by the weekend.

**Comment by valentingc** [comment]
Alright, thanks and take your time!

**Comment by madwizard-thomas** [comment]
Thanks for fixing my PR!

**Comment by Kane610** [comment]
PR is up https://github.com/home-assistant/core/pull/64873

**Pull request merged**
